temp disable workflows

diff --git a/.github/workflows/sqlite.yaml b/.github/workflows/sqlite.yaml
--- a/.github/workflows/sqlite.yaml
+++ b/.github/workflows/sqlite.yaml
@@ -1,61 +1,61 @@
-name: SQLite
+# name: SQLite
 
-on:
-  push:
-    branches: [main]
-    paths-ignore:
-      - '**.md'
-  pull_request:
-    branches: [main]
-    paths-ignore:
-      - '**.md'
-jobs:
-  ci:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Setup Go env
-        uses: actions/setup-go@v3
-        with:
-          go-version: "^1.20.4"
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 2
-      - name: Build binary
-        run: make dev
-        working-directory: cmd/warrant
-      - name: Install apirunner
-        run: go install github.com/warrant-dev/apirunner/cmd/apirunner@latest
-      - name: Start test server
-        id: start-server
-        run: ./cmd/warrant/bin/warrant > server.log 2>&1 &
-        env:
-          WARRANT_AUTOMIGRATE: true
-          WARRANT_PORT: 8000
-          WARRANT_LOGLEVEL: 0
-          WARRANT_ENABLEACCESSLOG: true
-          WARRANT_AUTHENTICATION_APIKEY: warrant_api_key
-          WARRANT_DATASTORE: sqlite
-          WARRANT_DATASTORE_SQLITE_DATABASE: warrant
-          WARRANT_DATASTORE_SQLITE_INMEMORY: true
-          WARRANT_DATASTORE_SQLITE_MIGRATIONSOURCE: file://./migrations/datastore/sqlite
-          WARRANT_EVENTSTORE: sqlite
-          WARRANT_EVENTSTORE_SQLITE_DATABASE: warrantEvents
-          WARRANT_EVENTSTORE_SQLITE_INMEMORY: true
-          WARRANT_EVENTSTORE_SQLITE_MIGRATIONSOURCE: file://./migrations/eventstore/sqlite
-          WARRANT_EVENTSTORE_SYNCHRONIZEEVENTS: true
-      - name: Run apirunner tests
-        run: |
-          sleep 3
-          apirunner tests/ tests/ci-apirunner.conf
-      - name: Shutdown test server
-        if: success() || (failure() && steps.start-server.outcome == 'success')
-        run: kill -9 `lsof -i:8000 -t`
-      - name: Archive server log
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: server-log
-          path: server.log
-          if-no-files-found: warn
-          retention-days: 5
+# on:
+#   push:
+#     branches: [main]
+#     paths-ignore:
+#       - '**.md'
+#   pull_request:
+#     branches: [main]
+#     paths-ignore:
+#       - '**.md'
+# jobs:
+#   ci:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Setup Go env
+#         uses: actions/setup-go@v3
+#         with:
+#           go-version: "^1.20.4"
+#       - name: Checkout
+#         uses: actions/checkout@v3
+#         with:
+#           fetch-depth: 2
+#       - name: Build binary
+#         run: make dev
+#         working-directory: cmd/warrant
+#       - name: Install apirunner
+#         run: go install github.com/warrant-dev/apirunner/cmd/apirunner@latest
+#       - name: Start test server
+#         id: start-server
+#         run: ./cmd/warrant/bin/warrant > server.log 2>&1 &
+#         env:
+#           WARRANT_AUTOMIGRATE: true
+#           WARRANT_PORT: 8000
+#           WARRANT_LOGLEVEL: 0
+#           WARRANT_ENABLEACCESSLOG: true
+#           WARRANT_AUTHENTICATION_APIKEY: warrant_api_key
+#           WARRANT_DATASTORE: sqlite
+#           WARRANT_DATASTORE_SQLITE_DATABASE: warrant
+#           WARRANT_DATASTORE_SQLITE_INMEMORY: true
+#           WARRANT_DATASTORE_SQLITE_MIGRATIONSOURCE: file://./migrations/datastore/sqlite
+#           WARRANT_EVENTSTORE: sqlite
+#           WARRANT_EVENTSTORE_SQLITE_DATABASE: warrantEvents
+#           WARRANT_EVENTSTORE_SQLITE_INMEMORY: true
+#           WARRANT_EVENTSTORE_SQLITE_MIGRATIONSOURCE: file://./migrations/eventstore/sqlite
+#           WARRANT_EVENTSTORE_SYNCHRONIZEEVENTS: true
+#       - name: Run apirunner tests
+#         run: |
+#           sleep 3
+#           apirunner tests/ tests/ci-apirunner.conf
+#       - name: Shutdown test server
+#         if: success() || (failure() && steps.start-server.outcome == 'success')
+#         run: kill -9 `lsof -i:8000 -t`
+#       - name: Archive server log
+#         if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: server-log
+#           path: server.log
+#           if-no-files-found: warn
+#           retention-days: 5
